<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="KyraGuy">

<title>Lab5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Lab5_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab5_files/libs/quarto-html/quarto.js"></script>
<script src="Lab5_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab5_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab5_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab5_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab5_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab5_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab5_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab5_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Lab5_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="Lab5_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="Lab5_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="Lab5_files/libs/leaflet-1.3.1/leaflet.js"></script>
<link href="Lab5_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="Lab5_files/libs/proj4-2.6.2/proj4.min.js"></script>
<script src="Lab5_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="Lab5_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="Lab5_files/libs/leaflet-binding-2.2.0/leaflet.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>KyraGuy </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">1 &amp; 2.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:data.table':

    between, first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dtplyr)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"met_all.gz"</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">download.file</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">url =</span> <span class="st">"https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">destfile =</span> <span class="st">"met_all.gz"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">method   =</span> <span class="st">"libcurl"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">timeout  =</span> <span class="dv">60</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a> met <span class="ot">&lt;-</span> data.table<span class="sc">::</span><span class="fu">fread</span>(<span class="st">"met_all.gz"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Download the data</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>stations <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>stations[, USAF <span class="sc">:</span><span class="er">=</span> <span class="fu">as.integer</span>(USAF)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in eval(jsub, SDenv, parent.frame()): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dealing with NAs and 999999</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>stations[, USAF   <span class="sc">:</span><span class="er">=</span> <span class="fu">fifelse</span>(USAF <span class="sc">==</span> <span class="dv">999999</span>, <span class="cn">NA_integer_</span>, USAF)]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>stations[, CTRY   <span class="sc">:</span><span class="er">=</span> <span class="fu">fifelse</span>(CTRY <span class="sc">==</span> <span class="st">""</span>, <span class="cn">NA_character_</span>, CTRY)]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>stations[, STATE  <span class="sc">:</span><span class="er">=</span> <span class="fu">fifelse</span>(STATE <span class="sc">==</span> <span class="st">""</span>, <span class="cn">NA_character_</span>, STATE)]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecting the three relevant columns, and keeping unique records</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>stations <span class="ot">&lt;-</span> <span class="fu">unique</span>(stations[, <span class="fu">list</span>(USAF, CTRY, STATE)])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping NAs</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>stations <span class="ot">&lt;-</span> stations[<span class="sc">!</span><span class="fu">is.na</span>(USAF)]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing duplicates</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>stations[, n <span class="sc">:</span><span class="er">=</span> <span class="dv">1</span><span class="sc">:</span>.N, by <span class="ot">=</span> .(USAF)]</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>stations <span class="ot">&lt;-</span> stations[n <span class="sc">==</span> <span class="dv">1</span>,][, n <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-1" class="level1">
<h1>3.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">merge</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Data</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x     =</span> met,      </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y     =</span> stations, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># List of variables to match</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by.x  =</span> <span class="st">"USAFID"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">by.y  =</span> <span class="st">"USAF"</span>, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Which obs to keep?</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.x =</span> <span class="cn">TRUE</span>,      </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.y =</span> <span class="cn">FALSE</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2377343</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>stations[, n <span class="sc">:</span><span class="er">=</span> <span class="dv">1</span><span class="sc">:</span>.N, by <span class="ot">=</span> .(USAF)]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>stations <span class="ot">&lt;-</span> stations[n <span class="sc">==</span> <span class="dv">1</span>,][, n <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">merge</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Data</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x     =</span> met,      </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y     =</span> stations, </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># List of variables to match</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">by.x  =</span> <span class="st">"USAFID"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">by.y  =</span> <span class="st">"USAF"</span>, </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Which obs to keep?</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.x =</span> <span class="cn">TRUE</span>,      </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">all.y =</span> <span class="cn">FALSE</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="question-1" class="level1">
<h1>Question 1</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a> median_values <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarize</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Median_Temperature =</span> <span class="fu">median</span>(temp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Median_Wind_Speed =</span> <span class="fu">median</span>(wind.sp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Median_Atmospheric_Pressure =</span> <span class="fu">median</span>(atm.press, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(median_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Median_Temperature Median_Wind_Speed Median_Atmospheric_Pressure
1               23.5               2.1                      1014.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a> closest_station <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">arrange</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">abs</span>(temp <span class="sc">-</span> median_values<span class="sc">$</span>Median_Temperature),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">abs</span>(wind.sp <span class="sc">-</span> median_values<span class="sc">$</span>Median_Wind_Speed),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>         <span class="fu">abs</span>(atm.press <span class="sc">-</span> median_values<span class="sc">$</span>Median_Atmospheric_Pressure)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>     ) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>     <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">print</span>(closest_station)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   USAFID WBAN year month day hour min   lat     lon elev wind.dir wind.dir.qc
1: 722246 3844 2019     8  11    9  56 30.65 -86.523   59      280           1
   wind.type.code wind.sp wind.sp.qc ceiling.ht ceiling.ht.qc ceiling.ht.method
1:              N     2.1          1      22000             1                 9
   sky.cond vis.dist vis.dist.qc vis.var vis.var.qc temp temp.qc dew.point
1:        N    16093           1       9          9 23.5       1      23.5
   dew.point.qc atm.press atm.press.qc  rh CTRY STATE
1:            1    1014.1            1 100   US    FL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>quantiles <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Latitude =</span> <span class="fu">quantile</span>(lat, <span class="at">probs =</span> <span class="fl">0.5</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Longitude =</span> <span class="fu">quantile</span>(lon, <span class="at">probs =</span> <span class="fl">0.5</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>representative_stations <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(lat <span class="sc">-</span> quantiles<span class="sc">$</span>Median_Latitude),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(lon <span class="sc">-</span> quantiles<span class="sc">$</span>Median_Longitude)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(representative_stations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   USAFID WBAN year month day hour min   lat     lon elev wind.dir wind.dir.qc
1: 720636  222 2019     8   1    0  15 38.35 -93.683  251       90           5
2: 720636  222 2019     8   1    0  35 38.35 -93.683  251       70           5
3: 720636  222 2019     8   1    0  55 38.35 -93.683  251       20           5
   wind.type.code wind.sp wind.sp.qc ceiling.ht ceiling.ht.qc ceiling.ht.method
1:              N     2.1          5       3353             5                 M
2:              N     2.1          5       3353             5                 M
3:              N     6.7          5       3353             5                 M
   sky.cond vis.dist vis.dist.qc vis.var vis.var.qc temp temp.qc dew.point
1:        N    16093           5       N          5   24       5        20
2:        N    16093           5       N          5   23       5        20
3:        N    16093           5       N          5   23       5        20
   dew.point.qc atm.press atm.press.qc       rh CTRY STATE
1:            5        NA            9 78.41305   US    MO
2:            5        NA            9 83.28225   US    MO
3:            5        NA            9 83.28225   US    MO</code></pre>
</div>
</div>
<p>The median values are Temp (23.5), Wind Speed (2.1), and Atmospheric Pressure (1014.1). The median station is 722246 in FL. Stations in Montanna came up after looking at the quartiles.</p>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>representative_stations <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(STATE) <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">euclidean =</span> <span class="fu">sqrt</span>((lat <span class="sc">-</span> <span class="fu">mean</span>(lat))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (lon <span class="sc">-</span> <span class="fu">mean</span>(lon))<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(STATE, euclidean, lat) <span class="sc">%&gt;%</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(STATE, USAFID, lat, lon, euclidean)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>representative_stations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 5
# Groups:   STATE [48]
   STATE USAFID   lat    lon euclidean
   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
 1 AL    722300  33.2  -86.8    0.441 
 2 AR    723429  35.3  -93.1    0.411 
 3 AZ    723745  34.3 -111.     0.396 
 4 CA    723890  36.8 -120.     0.410 
 5 CO    726396  39.1 -106.     0.196 
 6 CT    725027  41.5  -72.8    0.114 
 7 DE    724088  39.1  -75.5    0.0284
 8 FL    722014  28.5  -82.5    0.149 
 9 GA    722175  32.6  -83.6    0.270 
10 IA    725466  41.7  -93.6    0.180 
# ℹ 38 more rows</code></pre>
</div>
</div>
<p>The station chosen is USAFID 724420.</p>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>  state_midpoint <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(STATE) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">Midpoint_Latitude =</span> <span class="fu">mean</span>(lat),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">Midpoint_Longitude =</span> <span class="fu">mean</span>(lon)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a> find_closeststation <span class="ot">&lt;-</span> <span class="cf">function</span>(point, stations) {</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  distances <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((stations<span class="sc">$</span>lat <span class="sc">-</span> point<span class="sc">$</span>mid_lat)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (stations<span class="sc">$</span>lon <span class="sc">-</span> point<span class="sc">$</span>mid_lon)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  closeststation <span class="ot">&lt;-</span> stations[<span class="fu">min</span>(distances), ]</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(closeststation)}</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a> closest_stations <span class="ot">&lt;-</span> state_midpoint <span class="sc">%&gt;%</span> <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> <span class="fu">do</span>(<span class="fu">find_closeststation</span>(., dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(distances): no non-missing arguments to min; returning Inf</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in `[.data.table`(stations, min(distances), ): NAs introduced by
coercion to integer range</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a> repandclosest <span class="ot">&lt;-</span> <span class="fu">cbind</span>(state_midpoint, representative_stations) </span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>repandclosest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   STATE Midpoint_Latitude Midpoint_Longitude STATE USAFID    lat      lon
1     AL          32.75554          -86.65318    AL 722300 33.177  -86.783
2     AR          35.18904          -92.68849    AR 723429 35.259  -93.093
3     AZ          33.91659         -111.54154    AZ 723745 34.257 -111.339
4     CA          36.50457         -120.03186    CA 723890 36.767 -119.717
5     CO          39.12441         -105.69753    CO 726396 39.050 -105.516
6     CT          41.48119          -72.71733    CT 725027 41.510  -72.828
7     DE          39.15950          -75.47708    DE 724088 39.133  -75.467
8     FL          28.33518          -82.39921    FL 722014 28.474  -82.454
9     GA          32.56718          -83.33168    GA 722175 32.640  -83.592
10    IA          41.85552          -93.49382    IA 725466 41.691  -93.566
11    ID          45.02638         -115.17229    ID 725864 44.890 -116.101
12    IL          40.22512          -88.81862    IL 724397 40.477  -88.916
13    IN          40.51988          -86.33665    IN 720961 40.711  -86.375
14    KS          38.32236          -97.96264    KS 724506 38.066  -97.861
15    KY          37.50187          -85.11900    KY 720448 37.578  -84.770
16    LA          30.51183          -91.71927    LA 720967 30.718  -91.479
17    MA          42.03785          -70.99897    MA 725068 41.876  -71.021
18    MD          39.06089          -76.82664    MD 722244 38.981  -76.922
19    ME          44.60213          -69.57403    ME 726073 44.533  -69.667
20    MI          43.41830          -84.69928    MI 725405 43.322  -84.688
21    MN          45.23699          -94.31785    MN 726583 45.147  -94.507
22    MO          38.28066          -92.75603    MO 724459 38.096  -92.553
23    MS          33.05395          -89.77502    MS 722350 32.321  -90.078
24    MT          45.81591         -108.98264    MT 726770 45.808 -108.543
25    NC          35.55578          -79.17800    NC 722201 35.582  -79.101
26    ND          47.75992         -100.08523    ND 720867 48.390 -100.024
27    NE          41.26627          -98.59109    NE 725520 40.967  -98.317
28    NH          43.54523          -71.55302    NH 726155 43.567  -71.433
29    NJ          40.31345          -74.47269    NJ 724090 40.033  -74.353
30    NM          34.30261         -105.89839    NM 722677 35.000 -105.670
31    NV          38.68753         -117.21082    NV 724855 38.060 -117.087
32    NY          42.40904          -75.50851    NY 725150 42.209  -75.980
33    OH          40.40494          -82.94026    OH 720928 40.280  -83.115
34    OK          35.55121          -97.15465    OK 723540 35.417  -97.383
35    OR          43.31317         -122.79527    OR 725975 42.600 -123.364
36    PA          40.62764          -77.62156    PA 725128 40.849  -77.849
37    RI          41.62342          -71.49612    RI 725074 41.597  -71.412
38    SC          33.92152          -80.79047    SC 723105 33.921  -80.801
39    SD          44.22241          -99.86385    SD 726560 44.381 -100.285
40    TN          35.70926          -86.55706    TN 723273 36.009  -86.520
41    TX          31.12371          -98.01178    TX 720647 31.106  -98.196
42    UT          39.38740         -112.33426    UT 725724 40.219 -111.723
43    VA          37.54765          -78.21585    VA 724017 37.358  -78.438
44    VT          44.35726          -72.58793    VT 726145 44.204  -72.562
45    WA          47.41976         -122.56157    WA 720388 47.104 -122.287
46    WI          44.46353          -89.93145    WI 726452 44.360  -89.839
47    WV          38.72488          -80.58560    WV 720328 39.000  -80.274
48    WY          42.72014         -108.18546    WY 726720 43.067 -108.450
    euclidean
1  0.44100224
2  0.41051820
3  0.39610992
4  0.40988686
5  0.19618481
6  0.11435489
7  0.02835187
8  0.14923889
9  0.27031495
10 0.17965421
11 0.93867109
12 0.27004682
13 0.19492582
14 0.27577228
15 0.35720727
16 0.31660468
17 0.16333791
18 0.12439979
19 0.11585840
20 0.09696293
21 0.20946744
22 0.27444673
23 0.79310830
24 0.43971340
25 0.08133960
26 0.63304562
27 0.40581731
28 0.12197381
29 0.30491757
30 0.73383136
31 0.63962669
32 0.51217378
33 0.21480860
34 0.26486873
35 0.91217904
36 0.31737646
37 0.08816932
38 0.01053936
39 0.45002116
40 0.30202578
41 0.18507428
42 1.03208345
43 0.29209064
44 0.15544135
45 0.41844024
46 0.13879981
47 0.41567668
48 0.43622371</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leaflet</span>(<span class="at">data =</span> repandclosest) <span class="sc">%&gt;%</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addTiles</span>() <span class="sc">%&gt;%</span></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addCircleMarkers</span>(</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lng =</span> <span class="sc">~</span>lon,</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">lat =</span> <span class="sc">~</span>lat,</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="st">'stations'</span>,</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fillColor =</span> ,</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fillOpacity =</span> <span class="fl">0.7</span>,</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">radius =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-d7d13334263aad9af5b7" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d7d13334263aad9af5b7">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"https://openstreetmap.org/copyright/\">OpenStreetMap<\/a>,  <a href=\"https://opendatacommons.org/licenses/odbl/\">ODbL<\/a>"}]},{"method":"addCircleMarkers","args":[[33.177,35.259,34.257,36.767,39.05,41.51,39.133,28.474,32.64,41.691,44.89,40.477,40.711,38.066,37.578,30.718,41.876,38.981,44.533,43.322,45.147,38.096,32.321,45.808,35.582,48.39,40.967,43.567,40.033,35,38.06,42.209,40.28,35.417,42.6,40.849,41.597,33.921,44.381,36.009,31.106,40.219,37.358,44.204,47.104,44.36,39,43.067],[-86.783,-93.093,-111.339,-119.717,-105.516,-72.828,-75.467,-82.45400000000001,-83.592,-93.566,-116.101,-88.916,-86.375,-97.861,-84.77,-91.479,-71.021,-76.922,-69.667,-84.688,-94.50700000000001,-92.553,-90.078,-108.543,-79.101,-100.024,-98.31700000000001,-71.43300000000001,-74.35300000000001,-105.67,-117.087,-75.98,-83.11499999999999,-97.383,-123.364,-77.849,-71.41200000000001,-80.801,-100.285,-86.52,-98.196,-111.723,-78.438,-72.562,-122.287,-89.839,-80.274,-108.45],3,null,"stations",{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.7},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[28.474,48.39],"lng":[-123.364,-69.667]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="question-4" class="level1">
<h1>Question 4</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(STATE) <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarize</span>(</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mean_Temperature =</span> <span class="fu">mean</span>(temp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mean_Wind_Speed =</span> <span class="fu">mean</span>(wind.sp, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mean_Atmospheric_Pressure =</span> <span class="fu">mean</span>(atm.press, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-8"><a href="#cb120-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-9"><a href="#cb120-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-10"><a href="#cb120-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 4
   STATE Mean_Temperature Mean_Wind_Speed Mean_Atmospheric_Pressure
   &lt;chr&gt;            &lt;dbl&gt;           &lt;dbl&gt;                     &lt;dbl&gt;
 1 AL                26.2            1.57                     1016.
 2 AR                26.2            1.84                     1015.
 3 AZ                28.8            2.98                     1011.
 4 CA                22.4            2.61                     1013.
 5 CO                19.5            3.08                     1014.
 6 CT                22.3            2.19                     1015.
 7 DE                24.6            2.76                     1015.
 8 FL                27.5            2.50                     1015.
 9 GA                26.5            1.51                     1015.
10 IA                21.3            2.57                     1015.
# ℹ 38 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>mean_values <span class="ot">&lt;-</span> mean_values <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categorical =</span> <span class="fu">cut</span>(</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>    Mean_Temperature,</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="fl">18.1668</span>, <span class="dv">20</span>, <span class="dv">25</span>,  <span class="fl">29.59743</span>),</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">right =</span> F,</span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"low temp"</span>, <span class="st">"mid temp"</span>, <span class="st">"high temp"</span>),</span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">ordered_result =</span> F))</span>
<span id="cb122-8"><a href="#cb122-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb122-9"><a href="#cb122-9" aria-hidden="true" tabindex="-1"></a>summaries <span class="ot">&lt;-</span> mean_values <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(categorical) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">number_entries =</span> <span class="fu">n</span>(),</span>
<span id="cb122-10"><a href="#cb122-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Avg_Temperature =</span> <span class="fu">mean</span>(Mean_Temperature, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb122-11"><a href="#cb122-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Avg_Wind_Speed =</span> <span class="fu">mean</span>(Mean_Wind_Speed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb122-12"><a href="#cb122-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Avg_Atmospheric_Pressure =</span> <span class="fu">mean</span>(Mean_Atmospheric_Pressure, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb122-13"><a href="#cb122-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-14"><a href="#cb122-14" aria-hidden="true" tabindex="-1"></a>summaries</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  categorical number_entries Avg_Temperature Avg_Wind_Speed
  &lt;fct&gt;                &lt;int&gt;           &lt;dbl&gt;          &lt;dbl&gt;
1 low temp                11            18.7           2.55
2 mid temp                25            22.6           2.39
3 high temp               12            27.0           2.43
# ℹ 1 more variable: Avg_Atmospheric_Pressure &lt;dbl&gt;</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>